-- Table: knowledge.kpi_company

-- DROP TABLE kpi_company;

CREATE TABLE kpi_company
(
    location_id character varying(4) COLLATE pg_catalog."default",
    location character varying(50) COLLATE pg_catalog."default",
    site character varying(20) COLLATE pg_catalog."default",
    group_site character varying(50) COLLATE pg_catalog."default",
    region character varying(50) COLLATE pg_catalog."default",
    country character varying(50) COLLATE pg_catalog."default"
)

TABLESPACE pg_default;

ALTER TABLE kpi_company
    OWNER to postgres;
	
INSERT INTO KPI_COMPANY (LOCATION_ID, LOCATION, SITE, GROUP_SITE, REGION, COUNTRY) VALUES ('1140', 'ASI Bobst Grenchen AG', 'ASI', 'ASI', '', '');
INSERT INTO KPI_COMPANY (LOCATION_ID, LOCATION, SITE, GROUP_SITE, REGION, COUNTRY) VALUES ('3010', 'BAM-TN Bobst Af. & M.East', 'BAM', 'BAM', '', '');
INSERT INTO KPI_COMPANY (LOCATION_ID, LOCATION, SITE, GROUP_SITE, REGION, COUNTRY) VALUES ('1340', 'BBN Bobst Benelux (br.off', 'BBN', 'BOG', '', '');
INSERT INTO KPI_COMPANY (LOCATION_ID, LOCATION, SITE, GROUP_SITE, REGION, COUNTRY) VALUES ('1100', 'BBN Bobst Benelux NV', 'BBN', 'BOG', '', '');
INSERT INTO KPI_COMPANY (LOCATION_ID, LOCATION, SITE, GROUP_SITE, REGION, COUNTRY) VALUES ('2010', 'BBR Bobst Brasil', 'BBR', 'BBR', '', '');
INSERT INTO KPI_COMPANY (LOCATION_ID, LOCATION, SITE, GROUP_SITE, REGION, COUNTRY) VALUES ('4140', 'BCL Bobst Changzhou Co.Lt', 'BCL', 'BCL', '', '');
INSERT INTO KPI_COMPANY (LOCATION_ID, LOCATION, SITE, GROUP_SITE, REGION, COUNTRY) VALUES ('1120', 'BEE Bobst Ctrl Eur s.r.o', 'BEE', 'BEE', '', '');
INSERT INTO KPI_COMPANY (LOCATION_ID, LOCATION, SITE, GROUP_SITE, REGION, COUNTRY) VALUES ('1210', 'BES Bobst Ibérica S.L.', 'BES', 'BES', '', '');
INSERT INTO KPI_COMPANY (LOCATION_ID, LOCATION, SITE, GROUP_SITE, REGION, COUNTRY) VALUES ('1030', 'BFA Bobst Paris', 'BFA', 'BFA', '', '');
INSERT INTO KPI_COMPANY (LOCATION_ID, LOCATION, SITE, GROUP_SITE, REGION, COUNTRY) VALUES ('1380', 'BFL Bobst Firenze S.r.l', 'BFL', 'BFL', '', '');
INSERT INTO KPI_COMPANY (LOCATION_ID, LOCATION, SITE, GROUP_SITE, REGION, COUNTRY) VALUES ('1160', 'BGL Bobst (UK Ire) Ltd', 'BGL', 'BGL', '', '');
INSERT INTO KPI_COMPANY (LOCATION_ID, LOCATION, SITE, GROUP_SITE, REGION, COUNTRY) VALUES ('1200', 'BGS-DK Bobst Scandin. ApS', 'BGS', 'BGS', '', '');
INSERT INTO KPI_COMPANY (LOCATION_ID, LOCATION, SITE, GROUP_SITE, REGION, COUNTRY) VALUES ('1350', 'BGS-SE Bobst Scand. ApS', 'BGS', 'BGS', '', '');
INSERT INTO KPI_COMPANY (LOCATION_ID, LOCATION, SITE, GROUP_SITE, REGION, COUNTRY) VALUES ('2030', 'BGU Bobst North America', 'BGU', 'BGU', '', '');
INSERT INTO KPI_COMPANY (LOCATION_ID, LOCATION, SITE, GROUP_SITE, REGION, COUNTRY) VALUES ('1150', 'BGV Bobst CIS LLC.', 'BGV', 'BGV', '', '');
INSERT INTO KPI_COMPANY (LOCATION_ID, LOCATION, SITE, GROUP_SITE, REGION, COUNTRY) VALUES ('4120', 'BID P.T. Bobst Jakarta', 'BID', 'BSEA', '', '');
INSERT INTO KPI_COMPANY (LOCATION_ID, LOCATION, SITE, GROUP_SITE, REGION, COUNTRY) VALUES ('4070', 'BIN Bobst India Pr. Ltd.', 'BIN', 'BIN', '', '');
INSERT INTO KPI_COMPANY (LOCATION_ID, LOCATION, SITE, GROUP_SITE, REGION, COUNTRY) VALUES ('4150', 'BIS Bobst Istanbul Packag', 'BIS', 'BIS', '', '');
INSERT INTO KPI_COMPANY (LOCATION_ID, LOCATION, SITE, GROUP_SITE, REGION, COUNTRY) VALUES ('4010', 'BJL Bobst Japan Ltd', 'BJL', 'BJL', '', '');
INSERT INTO KPI_COMPANY (LOCATION_ID, LOCATION, SITE, GROUP_SITE, REGION, COUNTRY) VALUES ('3040', 'BLG Bobst Lagos', 'BLG', 'BSEA', '', '');
INSERT INTO KPI_COMPANY (LOCATION_ID, LOCATION, SITE, GROUP_SITE, REGION, COUNTRY) VALUES ('2040', 'BLN Bobst Latin Amer Nort', 'BLN', 'BLN', '', '');
INSERT INTO KPI_COMPANY (LOCATION_ID, LOCATION, SITE, GROUP_SITE, REGION, COUNTRY) VALUES ('4090', 'BMA Bobst Malaysia', 'BMA', 'BSEA', '', '');
INSERT INTO KPI_COMPANY (LOCATION_ID, LOCATION, SITE, GROUP_SITE, REGION, COUNTRY) VALUES ('1110', 'BOG Bobst Meerbusch GmbH', 'BOG', 'BOG', '', '');
INSERT INTO KPI_COMPANY (LOCATION_ID, LOCATION, SITE, GROUP_SITE, REGION, COUNTRY) VALUES ('1130', 'BPL Bobst Polska Sp.z o.o', 'BPL', 'BPL', '', '');
INSERT INTO KPI_COMPANY (LOCATION_ID, LOCATION, SITE, GROUP_SITE, REGION, COUNTRY) VALUES ('1020', 'BSA Bobst Mex SA', 'BSA', 'BSA', '', '');
INSERT INTO KPI_COMPANY (LOCATION_ID, LOCATION, SITE, GROUP_SITE, REGION, COUNTRY) VALUES ('4060', 'BSL Bobst (Shanghai) Ltd', 'BSL', 'BSL', '', '');
INSERT INTO KPI_COMPANY (LOCATION_ID, LOCATION, SITE, GROUP_SITE, REGION, COUNTRY) VALUES ('4100', 'BTH Bobst (Thailand) Ltd.', 'BTH', 'BSEA', '', '');
INSERT INTO KPI_COMPANY (LOCATION_ID, LOCATION, SITE, GROUP_SITE, REGION, COUNTRY) VALUES ('4160', 'BVN Bobst Vietnam Co. Ltd', 'BVN', 'BSEA', '', '');
INSERT INTO KPI_COMPANY (LOCATION_ID, LOCATION, SITE, GROUP_SITE, REGION, COUNTRY) VALUES ('1320', 'FKG Bobst Bielefeld GmbH', 'FKG', 'FKG', '', '');
INSERT INTO KPI_COMPANY (LOCATION_ID, LOCATION, SITE, GROUP_SITE, REGION, COUNTRY) VALUES ('1270', 'GEN Bobst Manchester Ltd', 'GEN', 'GEN', '', '');
INSERT INTO KPI_COMPANY (LOCATION_ID, LOCATION, SITE, GROUP_SITE, REGION, COUNTRY) VALUES ('1260', 'ROT Bobst Italia SPA', 'ROT', 'ROT', '', '');
INSERT INTO KPI_COMPANY (LOCATION_ID, LOCATION, SITE, GROUP_SITE, REGION, COUNTRY) VALUES ('1060', 'SAM Bobst Lyon S.A.S.', 'SAM', 'SAM', '', '');
INSERT INTO KPI_COMPANY (LOCATION_ID, LOCATION, SITE, GROUP_SITE, REGION, COUNTRY) VALUES ('1090', 'SCH Bobst Italia SPA', 'SCH', 'SCH', '', '');

COMMIT TRANSACTION;
